### PR TITLE
Back to Reducer (time-travel debugging would have helped here)

### LINKED ISSUE #42: Query params sometimes gets stuck bouncing between two states in a loop
To try to reproduce:

Double click on two LTLAs in quick succession (keep trying until you get into the state) FYI @richardgoater

### PR DESCRIPTION
**Pull request by richardgoater**
Fixes #42

### CODE REVIEW

**Comment by theosanderson** [comment]
Thanks a lot for looking at this so fast!

**Comment by richardgoater** [comment]
I can see that the map loading state has disappeared, and the same inconsistency could happen when changing the "Color by" setting. I will try to get these in here.

We could add error handling for both as well, if we can think up some sort of UI for it

**Comment by richardgoater** [comment]
latest commit also means the tiles config **must** be provided as numbers - would be good to add this to the documentation

**Comment by theosanderson** [comment]
Woop!

**Comment by theosanderson** [comment]
🎉

**Pull request merged**
