### PR TITLE
Mobile charts

### PR DESCRIPTION
**Pull request by richardgoater**

### CODE REVIEW

**Comment by richardgoater** [comment]
yikes, sorry about the nasty rebase issues in this branch, should be able to fix it.

**Comment by theosanderson** [comment]
Super awesome. 

For maximum UX we could think about like flashing up an instruction about dragging after the button is pressed, but tbh the main thing is just avoiding it doing the zoom by default, which this achieves (and it achieves much more than that!).

**Comment by richardgoater** [comment]
I'd like to stop the tooltip showing after the range has been set, can quickly try to do this tomorrow but I also want to stop procrastinating on other stuff :)

**Comment by theosanderson** [comment]
> I'd like to stop the tooltip showing after the range has been set

To understand, what's the rationale for this?

**Comment by theosanderson** [comment]
Ah I guess you mean the way it suddenly appears, rather than preventing it ever appearing?

**Comment by richardgoater** [comment]
Yeah, I think you want to zoom to see how the curve changes but the tooltip
gets in the way

**Comment by theosanderson** [comment]
If the proposal is to totally disable the tooltip when ranges are set I might argue against that but let's chat :)

**Comment by richardgoater** [comment]
nah I agree that the tooltip is needed when zoomed in, just not at the exact moment the range has been applied. It's something to do with the fake hover state in touch mode, hopefully there's a workaround.

**Comment by theosanderson** [comment]
Awesome, yeah sounds great

**Comment by richardgoater** [comment]
Think this is the best it's going to get, the tooltip behaviour still isn't perfect but we don't have that much control over it.

**Review by theosanderson — APPROVED** [review]
💯 Super nice

**Pull request merged**
