### PR TITLE
Asynchronous lists.json loading

### PR DESCRIPTION
**Pull request by theosanderson**
Includes change of lists.json format: `default_date` becomes `initialDate` as in code.

Rolled the existing TileProvider into this, in part because in the future I think we may load tiles asynchronously too and this should be faster if we have the ability to do both in tandem.

### CODE REVIEW

**Comment by theosanderson** [comment]
I'll re-minify the JSONs before merging

**Comment by theosanderson** [comment]
Arghh this rebase has made this PR way too big accidentally - will make a new version

**Comment by richardgoater** [comment]
no worries dude, yeah squashing is annoying.

**Comment by theosanderson** [comment]
Oh no the rebase hasn't

**Pull request closed without merging**
