### PR TITLE
Location select

### PR DESCRIPTION
**Pull request by richardgoater**

### CODE REVIEW

**Comment by theosanderson** [comment]
Looks neat. I'm wondering about having the top option be `England overview` as an alternative (alongside) the button?

**Comment by richardgoater** [comment]
@theosanderson do you have a preference on:
image
or something like
image

**Comment by theosanderson** [comment]
I think I personally slightly prefer the second one because so many of them are LTLAs that I find the indentation a bit distracting, and because I think it slightly implies there will be another level at which one can choose. (One could have that hacky thing of an "-----" option between England and the rest.)

**Comment by richardgoater** [comment]
Don't mind the hack :) think the separation is good

**Comment by theosanderson** [comment]
Looks great to me!

**Review by theosanderson — APPROVED** [review]

**Pull request merged**
