### PR TITLE
Truncate R graph y axis

### PR DESCRIPTION
**Pull request by theosanderson**

### CODE REVIEW

**Comment by theosanderson** [comment]
I never know how one's meant to handle scoping in this sort of situation, do correct me!

**Comment by richardgoater** [comment]
> I never know how one's meant to handle scoping in this sort of situation, do correct me!

I think it would be worth wrapping it in `useMemo` just in case. The charts are probably over-rendering anyway, we could dig into that at some point.

**Comment by richardgoater** [comment]
Looks good! Nice one 👍

Sorry for the slow reply, I was over-optimising in my head. Ideally a chart component doesn't know the type of data it is rendering, but that is for a future refactor :)

**Comment by theosanderson** [comment]
> Looks good! Nice one 👍
> 
> Sorry for the slow reply, I was over-optimising in my head. Ideally a chart component doesn't know the type of data it is rendering, but that is for a future refactor :)

Do take your point that this is not longer just a "MultiLinePlot" component. TBH it already wasn't, as you say, todo

**Pull request merged**
