### PR TITLE
Integrated data version

### PR DESCRIPTION
**Pull request by richardgoater**
Thought this would be a bit nicer than buried in the footer, happy to discuss. Some notes:

* Used the ordinal format for days as it's in a sentence e.g. Data updated __1st__ May, but this is different to all other date formats in the app
* Mobile style could also be white with a border, but the grey band looks cool I think
* Also includes a clean-up of the lineage filter on mobile, I saw this was tweaked on covglobe 👍🏽

### CODE REVIEW

**Comment by theosanderson** [comment]
Looks great! (Possible potential for a tiny bit more whitespace above on desktop but I guess you've tried both!)

TBH I hadn't remembered that change on CovGlobe, it was probably an accident! But everything looks great to me here! (To be clear I'll revert CovGlobe to use CovInce itself soon, I just hacked stuff together for a starting point when we were having all those import issues)

**Review by theosanderson — APPROVED** [review]

**Comment by richardgoater** [comment]
Yeah I agree that there is a compromise with the whitespace. We can't really reduce the text size further, but we might be able to steal a few more pixels from the charts. I'll try it quickly.

**Review by theosanderson — APPROVED** [review]
LGTM

**Comment by theosanderson** [comment]
With the format like that my brain expects a colon after updated. But others may differ. Again, LGTM :D Thanks a lot

**Comment by theosanderson** [comment]
Ignore my colon thing, just tried it :)

**Pull request merged**
